"""update user table

Revision ID: 02832325b3ea
Revises: 226d15a93b1a
Create Date: 2024-06-16 13:54:06.949176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02832325b3ea"
down_revision: Union[str, None] = "226d15a93b1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.add_column(
        "users",
        sa.Column("password_hash", sa.LargeBinary(), nullable=False),
    )
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("users", sa.Column("role", sa.String(length=32), nullable=False))
    op.add_column("users", sa.Column("user_agreement", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "date_register",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_column("users", "date_register")
    op.drop_column("users", "is_active")
    op.drop_column("users", "user_agreement")
    op.drop_column("users", "role")
    op.drop_column("users", "email")
    op.drop_column("users", "password_hash")
    op.create_table(
        "posts",
        sa.Column(
            "title",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "body",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_posts_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_posts"),
    )
    # ### end Alembic commands ###
